# @package _global_
agent: sb3
agent_class: PPO

log_dir: .  # Logs in hydra folder
total_timesteps: 500000
n_eval_episodes: 5
verbose: 1
seed: 1

output_dir: logs/hydra
hydra:
  run:
    dir: ${output_dir}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${output_dir}/${now:%Y-%m-%d}/${now:%H-%M-%S}